version: '3'

services:
  client:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./site/conf/nginx:/etc/nginx
      - ./public:/usr/share/nginx/html:ro
      - ./site/certbot/conf:/etc/nginx/ssl
      - ./site/certbot/data:/var/www/certbot
      
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@domain.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
    volumes:
      - ./site/certbot/conf:/etc/letsencrypt
      - ./site/certbot/logs:/var/log/letsencrypt
      - ./site/certbot/data:/var/www/certbot
     
